
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[350] =
    {   0,
       30,   30,   35,   33,   30,   29,   30,   21,   28,   33,
       22,   23,   16,   14,   11,   15,   20,   17,    6,    6,
        6,    6,   10,   13,   12,   13,    9,    9,   24,   25,
        9,    9,    9,    9,    9,    9,   26,   33,   27,   30,
       13,   18,    0,    0,    6,    6,    6,    0,    0,    0,
       32,   31,    0,    0,    6,    6,    6,    0,    6,    6,
        6,    6,    9,    0,    8,    9,    9,    3,    9,    9,
        9,    9,   19,    0,    0,    6,    6,    6,    6,    0,
        8,    8,    8,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    9,    8,    9,    9,    7,    9,    9,    9,

        8,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    9,    8,    4,    9,
        9,    9,    9,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        9,    8,    7,    9,    9,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    9,    8,    2,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        9,    8,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    9,    8,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        9,    8,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    9,    8,
        6,    6,    6,    6,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,

        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,    1,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,    1,   35,    1,   32,    1,   36,   30,   37,   30,

       38,   39,   32,   40,   41,   32,   32,   42,   32,   43,
       44,   32,   32,   45,   46,   47,   48,   32,   49,   50,
       32,   32,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    2,    3,    1,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    6,
        7,    8,    8,    1,    1,    6,    6,    7,    6,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[532] =
    {   0,
        0,    0,  340, 2291, 2291, 2291,  330,  289, 2291,  309,
     2291, 2291, 2291, 2291, 2291,   40,   35,   57,   65,   61,
       88,   62, 2291,  286,  272,  265,    0,  116, 2291, 2291,
      249,  247,   31,  240,  223,  226, 2291,  208, 2291,  255,
     2291, 2291,   63,   83,   92,   93,  111,  100,  112,  105,
     2291, 2291,  113,  114,  132,  134,  150,    0,  140,  146,
      175,  185,    0,  109,  198,  205,  201,    0,  186,  183,
      142,  144, 2291,  124,  130,  152,  193,  218,  192,  156,
        0,    0,  142,  230,  233,  238,    0,  215,  234,  236,
      263,  259,    0,  286,  144,  140,    0,  105,   99,   75,

      148,  261,  281,  282,  307,  284,  319,  322,  327,    0,
      304,  323,  325,  335,  360,  351,    0,  383,    0,   65,
       63,   58,   53,  358,  378,  379,  380,  405,  415,  423,
      425,  427,    0,  424,  426,  428,  439,  453,  454,  455,
        0,  478,    0,   37,   30,    0,  473,  474,  475,  476,
      494,  495,  496,  504,  516,  524,    0,  508,  522,  530,
      536,  538,  542,  567,  209,    0,  590,    0,    0,  544,
      563,  564,  565,  585,  586,  606,  590,  605,  608,  617,
        0,  620,  621,  626,  631,  635,  636,  639,  664,  661,
        0,  687,  662,  682,  683,  684,  687,  702,  703,  728,

      705,  740,  743,    0,  724,  725,  744,  746,  755,  756,
      758,  759,  784,  455,    0,  807,  781,  802,  803,  804,
      806,  807,  822,  825,  850,  862,  865,  870,    0,    0,
        0,    0,    0,    0,    0,  847,    0,  866,   44,  868,
        0,  893,  888,    0,    0,    0,    0,    0,  891,    0,
      893,   30,  909,  911,  913, 2291,  914,    0,    0,  937,
      932,  950,    0,    0,    0,  973,    0,  983,    0,  993,
        0, 1003,    0, 1013,    0, 1023,    0, 1033,    0, 1043,
        0, 1053,    0, 1063,    0, 1073,    0, 1083,    0, 1093,
        0, 1103,    0, 1113,    0, 1123,    0, 1133,    0, 1143,

        0, 1153,    0, 1163,    0, 1173,    0, 1183,    0, 1193,
        0, 1203,    0, 1213,    0, 1223,    0, 1233,    0, 1243,
        0, 1253,    0, 1263,    0, 1273,    0, 1283,    0, 1293,
        0, 1303,    0, 1313,    0, 1323,    0, 1333,    0, 1343,
        0, 1353,    0, 1363,    0, 1373, 2291,    0, 2291, 1395,
     1400, 1405, 1409, 1414, 1419, 1424, 1429, 1435, 1439, 1441,
     1446, 1451, 1456, 1461, 1464, 1469, 1474, 1478, 1483, 1488,
     1493, 1498, 1503, 1508, 1512, 1517, 1522, 1527, 1532, 1536,
     1542, 1547, 1552, 1557, 1562, 1567, 1572, 1576, 1581, 1586,
     1591, 1596, 1600, 1606, 1611, 1616, 1621, 1626, 1631, 1636,

     1640, 1645, 1650, 1655, 1660, 1665, 1670, 1675, 1679, 1685,
     1690, 1695, 1700, 1705, 1710, 1715, 1720, 1725, 1730, 1734,
     1739, 1744, 1749, 1754, 1759, 1764, 1768, 1774, 1779, 1784,
     1789, 1794, 1799, 1804, 1809, 1814, 1819, 1823, 1828, 1833,
     1838, 1843, 1848, 1853, 1858, 1863, 1867, 1873, 1878, 1883,
     1888, 1893, 1898, 1903, 1908, 1913, 1918, 1922, 1927, 1932,
     1937, 1942, 1947, 1952, 1957, 1962, 1966, 1972, 1977, 1982,
     1987, 1992, 1997, 2002, 2007, 2012, 2017, 2022, 2026, 2031,
     2036, 2041, 2045, 2051, 2056, 2061, 2066, 2071, 2075, 2080,
     2085, 2090, 2095, 2100, 2105, 2110, 2115, 2120, 2125, 2130,

     2135, 2140, 2145, 2150, 2155, 2160, 2165, 2170, 2175, 2180,
     2185, 2190, 2195, 2200, 2205, 2210, 2215, 2220, 2225, 2230,
     2235, 2240, 2245, 2250, 2255, 2260, 2265, 2270, 2275, 2280,
     2285
    } ;

static yyconst flex_int16_t yy_def[532] =
    {   0,
      349,    1,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  350,  349,  349,  351,
      352,  352,  349,  349,  349,  349,  353,  353,  349,  349,
       28,  353,  353,  353,  353,  353,  349,  349,  349,  349,
      349,  349,  354,  355,  356,  357,  357,  358,  350,  359,
      349,  349,  360,  361,  362,  363,  364,  365,  366,  367,
      349,   61,  368,  359,  368,  368,  368,  368,  368,  368,
      368,  368,  349,  354,  369,  370,  371,  349,   78,  358,
       80,   64,  360,  372,  373,  374,  375,  376,  377,  378,
      349,  379,  380,  380,  380,  380,  380,  380,  380,  380,

      369,  381,  382,  383,  349,  384,  385,  386,  387,  388,
      389,  390,  391,  392,  349,  115,  393,  393,  393,  393,
      393,  393,  393,  394,  395,  396,  397,  349,  128,  398,
      399,  400,  401,  402,  403,  404,  405,  406,  407,  408,
      409,  409,  409,  409,  409,  409,  410,  411,  412,  413,
      414,  415,  416,  417,  418,  419,  420,  421,  422,  423,
      424,  425,  426,  349,  164,  427,  427,  427,  427,  428,
      429,  430,  431,  432,  433,  434,  434,  435,  436,  437,
      438,  439,  440,  441,  442,  443,  444,  445,  349,  446,
      447,  447,  448,  449,  450,  451,  452,  453,  454,  349,

      455,  456,  457,  458,  459,  460,  461,  462,  463,  464,
      465,  466,  349,  213,  467,  467,  468,  469,  470,  471,
      472,  473,  474,  475,  349,  476,  477,  478,  479,  214,
      214,  214,  214,  214,  214,  480,  214,  481,  214,  482,
      483,  483,  474,  243,  243,  243,  243,  243,  484,  243,
      485,  243,  486,  487,  488,  349,  482,  257,  489,  489,
      484,  488,  262,  257,  490,  490,  491,  491,  492,  492,
      493,  493,  494,  494,  495,  495,  496,  496,  497,  497,
      498,  498,  499,  499,  500,  500,  501,  501,  502,  502,
      503,  503,  504,  504,  505,  505,  506,  506,  507,  507,

      508,  508,  509,  509,  510,  510,  511,  511,  512,  512,
      513,  513,  514,  514,  515,  515,  516,  516,  517,  517,
      518,  518,  519,  519,  520,  520,  521,  521,  522,  522,
      523,  523,  524,  524,  525,  525,  526,  526,  527,  527,
      528,  528,  529,  529,  530,  530,  349,  531,    0,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349
    } ;

static yyconst flex_uint16_t yy_nxt[2345] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   27,   27,   29,   30,   27,   27,   31,   32,   27,
       33,   27,   27,   27,   34,   35,   27,   27,   36,   27,
       37,   38,   39,   43,   44,   44,   45,   46,   47,   47,
       47,   47,   47,   47,   47,   50,   51,   54,   54,   68,
       48,   52,   50,   69,   53,   53,  169,   48,   53,  168,
       54,   55,   56,   56,   57,   57,   57,   57,   54,   54,
      146,   50,   50,   48,  145,   50,   75,   58,   50,   50,

       48,   53,   50,   60,   61,   75,   75,  144,   77,   78,
       80,  143,   80,   48,   58,   64,  123,   64,   50,  349,
       48,  349,   48,   48,   75,   50,   64,   53,   64,   48,
       48,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   48,   50,   50,   50,   53,  122,   53,   48,   50,
       50,   50,  121,   53,   48,   54,   54,   54,   54,   53,
       48,   48,   50,   53,   50,   75,  349,   48,  349,   50,
       50,   50,   50,   54,   54,  120,   50,   50,   48,   50,
       50,  119,   48,   50,  100,   48,   99,   50,   53,   48,
       90,   90,   90,   90,   91,   92,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   50,   75,  106,  106,  106,
      106,  106,   50,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   48,  190,  190,  190,  190,   53,   98,
       48,   75,   97,  104,  104,  104,  104,  105,  106,  106,
      106,  106,  106,   53,   96,   50,   53,   53,   48,   53,
       95,   53,   50,   54,   54,   48,   54,   54,   40,   73,
       50,   54,   54,   50,   50,   72,   50,   50,   50,   71,
       50,   50,   53,   50,   75,   50,   53,   70,  114,  114,
      114,  114,  114,  114,  114,  115,  116,  116,   67,   50,
       66,   48,   41,   50,   75,   75,   50,   75,   48,   41,

       50,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,   48,   48,   41,   48,   42,   41,   53,   48,   48,
       75,   48,  127,  127,  127,  127,  127,  127,  127,  128,
      129,  129,   53,   40,   50,   53,   53,   48,   53,  349,
       53,   50,   54,   54,   48,   54,   54,  349,   53,   50,
       54,   54,   50,   50,  349,   50,   50,   50,  349,   50,
       50,  349,   50,  349,   50,   50,  140,  140,  140,  140,
      140,   75,   50,   53,  349,  138,  138,  138,  138,  139,
      140,  140,  140,  140,  140,  349,  349,  349,   48,  349,
       50,   75,   75,   75,  349,   48,  349,   50,  142,  142,

      142,  142,  142,  142,  142,  142,  142,  142,   48,   48,
       48,  349,  349,  349,  349,   48,   48,   48,   75,  349,
      151,  151,  151,  151,  152,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,   48,   53,   53,   53,   53,
       53,   53,   48,  349,  349,  349,   54,   54,   54,   54,
       54,   54,   53,   50,   50,   50,   50,   50,   50,  349,
       50,   50,   50,   50,   50,   50,   53,   53,   53,   50,
      240,  240,  240,  240,  240,  349,   50,  164,  165,  349,
      349,  349,  349,   50,   50,   50,   75,   75,   75,   75,
       50,   50,   50,  167,  167,  167,  167,  167,  167,  167,

      167,  167,  167,   48,   48,   48,   48,   75,   75,   75,
       48,   48,   48,   48,  349,  349,  349,   53,  176,  177,
      349,   53,  349,  349,   48,   48,   48,   54,   54,   53,
      349,   48,   48,   48,   50,   53,  349,   53,   50,   54,
       54,   50,  349,   53,  349,   50,   50,   54,   54,   53,
      349,   53,   50,   50,   50,   53,  349,   75,  349,   50,
       50,   50,  349,  349,  349,  349,   50,   50,   50,  349,
      349,  349,   50,   50,   48,   50,   75,   75,   75,   50,
       53,   48,  188,  188,  188,  189,  190,  190,  190,  190,
      190,  190,  349,   48,   48,   48,  349,   50,   75,   75,

       48,   48,   48,   75,   50,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,   48,   48,  349,   53,   75,
       48,   53,   48,   48,  200,  349,  349,   48,   54,   54,
       53,   54,   54,   53,   53,   50,   48,  349,   50,   53,
       54,   54,   50,   48,   53,   50,  349,   50,   53,   53,
       50,   50,   53,  349,   50,  349,   50,   50,   50,  349,
      349,   50,  349,   50,  349,   50,   50,  349,   50,   50,
      349,  349,   50,   50,   53,   75,   50,   53,  349,  212,
      212,  212,  212,  212,  212,  213,  214,  214,  214,  349,
      349,   50,   48,  349,   50,   75,   75,   75,   50,   48,

       75,   50,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,   48,   48,   48,   75,   75,   48,   53,   48,
       48,   48,  349,  349,   48,  349,  349,  349,   54,   54,
      349,  349,   48,   48,  349,   50,  349,   53,   53,   48,
       48,   75,   50,  224,  224,  224,  224,  224,  224,  225,
      223,  223,  223,   53,   50,   50,   53,   53,   48,   53,
      349,   50,   50,   54,   54,   48,   54,   54,   53,   53,
       50,   53,   53,   50,   50,  349,   50,   50,  349,  349,
       50,   50,  349,   50,  349,   50,   50,  349,   50,   50,
      349,  349,   50,   50,   75,   50,   50,   53,  349,  238,

      238,  238,  238,  239,  240,  240,  240,  240,  240,  349,
      349,   48,  349,  349,   50,   75,   75,   75,   48,   75,
       75,   50,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,   48,   48,   48,   75,   48,   48,   75,   48,
       48,   48,  349,   48,   48,  349,  349,  349,  349,  349,
      349,  349,   48,  349,  349,   48,  349,  349,  349,   48,
       53,  349,   48,   75,  349,  251,  251,  251,  251,  252,
      249,  249,  249,  249,  249,   53,  349,   50,   53,   53,
       48,   53,  349,   53,   50,   54,   54,   48,   54,   54,
      349,  349,   50,   54,   54,   50,   50,  349,   50,   50,

       50,   75,   50,   50,   75,   50,   75,   50,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,   48,  349,
      349,   48,   53,   48,   53,   48,   53,   53,   48,  349,
       48,  349,   54,   54,   54,   54,   54,   54,  349,   50,
      349,   50,  349,   50,   50,   75,   50,  349,   50,  349,
       50,   50,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,   48,   53,  349,  349,  349,  349,  349,   48,
      349,  349,  349,   54,   54,  349,  349,  349,  349,  349,
       50,  349,  349,  349,  349,  349,  349,   50,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  310,  310,

      310,  310,  310,  310,  310,  310,  310,  310,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,   49,   49,

      349,   49,   59,   59,   59,  349,   59,   62,   62,   62,
      349,   62,   63,   63,   63,   63,   63,   74,   74,  349,
       74,   44,   44,   44,  349,   44,   76,   76,   76,  349,
       76,   79,   79,   79,  349,   79,   81,  349,   81,   81,
       82,  349,   82,   82,   83,   83,  349,   83,   54,   54,
       54,  349,   54,   84,   84,   84,  349,   84,   85,   85,
       85,  349,   85,   86,   86,   86,  349,   86,   87,   87,
       87,   88,   88,   88,  349,   88,   89,   89,   89,  349,
       89,   93,   93,   93,   93,   93,  101,  101,  349,  101,
      102,  102,  102,  349,  102,  103,  103,  103,  349,  103,

      107,  107,  107,  349,  107,  108,  108,  108,  349,  108,
      109,  109,  109,  349,  109,  110,  110,  110,  110,  111,
      111,  111,  349,  111,  112,  112,  112,  349,  112,  113,
      113,  113,  349,  113,  116,  116,  116,  349,  116,  117,
      117,  117,  117,  117,  124,  124,  124,  349,  124,  125,
      125,  125,  349,  125,  126,  126,  126,  349,  126,  129,
      129,  129,  349,  129,  130,  130,  130,  349,  130,  131,
      131,  131,  349,  131,  132,  132,  132,  349,  132,  133,
      133,  133,  133,  134,  134,  134,  349,  134,  135,  135,
      135,  349,  135,  136,  136,  136,  349,  136,  137,  137,

      137,  349,  137,  141,  141,  141,  141,  141,  147,  147,
      147,  349,  147,  148,  148,  148,  349,  148,  149,  149,
      149,  349,  149,  150,  150,  150,  349,  150,  154,  154,
      154,  349,  154,  155,  155,  155,  349,  155,  156,  156,
      156,  349,  156,  157,  157,  157,  157,  158,  158,  158,
      349,  158,  159,  159,  159,  349,  159,  160,  160,  160,
      349,  160,  161,  161,  161,  349,  161,  162,  162,  162,
      349,  162,  163,  163,  163,  349,  163,  165,  165,  165,
      349,  165,  166,  166,  166,  166,  166,  170,  170,  170,
      349,  170,  171,  171,  171,  349,  171,  172,  172,  172,

      349,  172,  173,  173,  173,  349,  173,  174,  174,  174,
      349,  174,  175,  175,  175,  349,  175,  177,  177,  177,
      349,  177,  178,  178,  178,  349,  178,  179,  179,  179,
      349,  179,  180,  180,  180,  349,  180,  181,  181,  181,
      181,  182,  182,  182,  349,  182,  183,  183,  183,  349,
      183,  184,  184,  184,  349,  184,  185,  185,  185,  349,
      185,  186,  186,  186,  349,  186,  187,  187,  187,  349,
      187,  191,  191,  191,  191,  191,  193,  193,  193,  349,
      193,  194,  194,  194,  349,  194,  195,  195,  195,  349,
      195,  196,  196,  196,  349,  196,  197,  197,  197,  349,

      197,  198,  198,  198,  349,  198,  199,  199,  199,  349,
      199,  201,  201,  201,  349,  201,  202,  202,  202,  349,
      202,  203,  203,  203,  349,  203,  204,  204,  204,  204,
      205,  205,  205,  349,  205,  206,  206,  206,  349,  206,
      207,  207,  207,  349,  207,  208,  208,  208,  349,  208,
      209,  209,  209,  349,  209,  210,  210,  210,  349,  210,
      211,  211,  211,  349,  211,  214,  214,  214,  349,  214,
      215,  215,  215,  215,  215,  217,  217,  217,  349,  217,
      218,  218,  218,  349,  218,  219,  219,  219,  349,  219,
      220,  220,  220,  349,  220,  221,  221,  221,  349,  221,

      222,  222,  222,  349,  222,  223,  223,  223,  349,  223,
      226,  226,  226,  349,  226,  227,  227,  227,  349,  227,
      228,  228,  228,  349,  228,  229,  229,  229,  229,  230,
      230,  230,  349,  230,  231,  231,  231,  349,  231,  232,
      232,  232,  349,  232,  233,  233,  233,  349,  233,  234,
      234,  234,  349,  234,  235,  235,  235,  349,  235,  236,
      236,  236,  349,  236,  237,  237,  237,  349,  237,  241,
      241,  241,  241,  241,  243,  243,  243,  349,  243,  244,
      244,  244,  349,  244,  245,  245,  245,  349,  245,  246,
      246,  246,  349,  246,  247,  247,  247,  349,  247,  248,

      248,  248,  349,  248,  249,  249,  249,  349,  249,  250,
      250,  250,  349,  250,  253,  253,  253,  349,  253,  254,
      254,  254,  349,  254,  255,  255,  255,  349,  255,  256,
      256,  256,  256,  257,  257,  257,  349,  257,  258,  258,
      258,  349,  258,   54,   54,   54,  349,   54,  259,  259,
      259,  259,  259,   44,   44,   44,  349,   44,  261,  261,
      261,  349,  261,  262,  262,  262,  349,  262,  263,  263,
      263,  349,  263,  264,  264,  264,  349,  264,  265,  265,
      265,  265,  265,  267,  267,  267,  267,  267,  269,  269,
      269,  269,  269,  271,  271,  271,  271,  271,  273,  273,

      273,  273,  273,  275,  275,  275,  275,  275,  277,  277,
      277,  277,  277,  279,  279,  279,  279,  279,  281,  281,
      281,  281,  281,  283,  283,  283,  283,  283,  285,  285,
      285,  285,  285,  287,  287,  287,  287,  287,  289,  289,
      289,  289,  289,  291,  291,  291,  291,  291,  293,  293,
      293,  293,  293,  295,  295,  295,  295,  295,  297,  297,
      297,  297,  297,  299,  299,  299,  299,  299,  301,  301,
      301,  301,  301,  303,  303,  303,  303,  303,  305,  305,
      305,  305,  305,  307,  307,  307,  307,  307,  309,  309,
      309,  309,  309,  311,  311,  311,  311,  311,  313,  313,

      313,  313,  313,  315,  315,  315,  315,  315,  317,  317,
      317,  317,  317,  319,  319,  319,  319,  319,  321,  321,
      321,  321,  321,  323,  323,  323,  323,  323,  325,  325,
      325,  325,  325,  327,  327,  327,  327,  327,  329,  329,
      329,  329,  329,  331,  331,  331,  331,  331,  333,  333,
      333,  333,  333,  335,  335,  335,  335,  335,  337,  337,
      337,  337,  337,  339,  339,  339,  339,  339,  341,  341,
      341,  341,  341,  343,  343,  343,  343,  343,  345,  345,
      345,  345,  345,  347,  347,  347,  347,  347,   82,   82,
        3,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349
    } ;

static yyconst flex_int16_t yy_chk[2345] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   16,  252,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   17,   18,  239,  239,   33,
       16,   18,   17,   33,   20,   22,  145,   16,   19,  144,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
      123,   20,   22,   43,  122,   19,   44,   19,   20,   22,

       43,   21,   19,   21,   21,   45,   46,  121,   46,   46,
       48,  120,   48,   44,   19,   50,  100,   50,   21,   64,
       44,   64,   45,   46,   47,   21,   28,   54,   28,   45,
       46,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   47,   49,   53,   54,   55,   99,   56,   47,   49,
       53,   54,   98,   59,   74,   55,   55,   56,   56,   60,
       75,   74,   55,   57,   56,   76,   80,   75,   80,   55,
       59,   56,   83,   57,   57,   96,   60,   59,  101,   83,
       57,   95,   76,   60,   72,  101,   71,   57,   61,   76,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       62,   62,   62,   62,   62,   61,   77,   79,   79,   79,
       79,   79,   61,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   77,  165,  165,  165,  165,   88,   70,
       77,   78,   69,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   84,   67,   88,   85,   89,   78,   90,
       66,   86,   88,   84,   84,   78,   85,   85,   40,   38,
       84,   86,   86,   85,   89,   36,   90,   84,   86,   35,
       85,   89,   92,   90,  102,   86,   91,   34,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   32,   92,
       31,  102,   26,   91,  103,  104,   92,  106,  102,   25,

       91,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,  103,  104,   24,  106,   10,    8,  111,  103,  104,
      105,  106,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  107,    7,  111,  108,  112,  105,  113,    3,
      109,  111,  107,  107,  105,  108,  108,    0,  114,  107,
      109,  109,  108,  112,    0,  113,  107,  109,    0,  108,
      112,    0,  113,    0,  109,  114,  116,  116,  116,  116,
      116,  124,  114,  115,    0,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,    0,    0,    0,  124,    0,
      115,  125,  126,  127,    0,  124,    0,  115,  118,  118,

      118,  118,  118,  118,  118,  118,  118,  118,  125,  126,
      127,    0,    0,    0,    0,  125,  126,  127,  128,    0,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      129,  129,  129,  129,  129,  128,  130,  134,  131,  135,
      132,  136,  128,    0,    0,    0,  130,  130,  131,  131,
      132,  132,  137,  130,  134,  131,  135,  132,  136,    0,
      130,  134,  131,  135,  132,  136,  138,  139,  140,  137,
      214,  214,  214,  214,  214,    0,  137,  139,  139,    0,
        0,    0,    0,  138,  139,  140,  147,  148,  149,  150,
      138,  139,  140,  142,  142,  142,  142,  142,  142,  142,

      142,  142,  142,  147,  148,  149,  150,  151,  152,  153,
      147,  148,  149,  150,    0,    0,    0,  154,  152,  152,
        0,  158,    0,    0,  151,  152,  153,  154,  154,  155,
        0,  151,  152,  153,  154,  159,    0,  156,  158,  155,
      155,  154,    0,  160,    0,  158,  155,  156,  156,  161,
        0,  162,  159,  155,  156,  163,    0,  170,    0,  159,
      160,  156,    0,    0,    0,    0,  161,  160,  162,    0,
        0,    0,  163,  161,  170,  162,  171,  172,  173,  163,
      164,  170,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,    0,  171,  172,  173,    0,  164,  174,  175,

      171,  172,  173,  177,  164,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  174,  175,    0,  178,  176,
      177,  179,  174,  175,  176,    0,    0,  177,  178,  178,
      180,  179,  179,  182,  183,  178,  176,    0,  179,  184,
      180,  180,  178,  176,  185,  179,    0,  180,  186,  187,
      182,  183,  188,    0,  180,    0,  184,  182,  183,    0,
        0,  185,    0,  184,    0,  186,  187,    0,  185,  188,
        0,    0,  186,  187,  190,  193,  188,  189,    0,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,    0,
        0,  190,  193,    0,  189,  194,  195,  196,  190,  193,

      197,  189,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  194,  195,  196,  198,  199,  197,  201,  194,
      195,  196,    0,    0,  197,    0,    0,    0,  201,  201,
        0,    0,  198,  199,    0,  201,    0,  205,  206,  198,
      199,  200,  201,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  202,  205,  206,  203,  207,  200,  208,
        0,  205,  206,  202,  202,  200,  203,  203,  209,  210,
      202,  211,  212,  203,  207,    0,  208,  202,    0,    0,
      203,  207,    0,  208,    0,  209,  210,    0,  211,  212,
        0,    0,  209,  210,  217,  211,  212,  213,    0,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,    0,
        0,  217,    0,    0,  213,  218,  219,  220,  217,  221,
      222,  213,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  218,  219,  220,  223,  221,  222,  224,  218,
      219,  220,    0,  221,  222,    0,    0,    0,    0,    0,
        0,    0,  223,    0,    0,  224,    0,    0,    0,  223,
      236,    0,  224,  225,    0,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  226,    0,  236,  227,  238,
      225,  240,    0,  228,  236,  226,  226,  225,  227,  227,
        0,    0,  226,  228,  228,  227,  238,    0,  240,  226,

      228,  243,  227,  238,  249,  240,  251,  228,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  243,    0,
        0,  249,  253,  251,  254,  243,  255,  257,  249,    0,
      251,    0,  253,  253,  254,  254,  255,  255,    0,  253,
        0,  254,    0,  255,  257,  261,  253,    0,  254,    0,
      255,  257,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  261,  262,    0,    0,    0,    0,    0,  261,
        0,    0,    0,  262,  262,    0,    0,    0,    0,    0,
      262,    0,    0,    0,    0,    0,    0,  262,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  350,  350,

        0,  350,  351,  351,  351,    0,  351,  352,  352,  352,
        0,  352,  353,  353,  353,  353,  353,  354,  354,    0,
      354,  355,  355,  355,    0,  355,  356,  356,  356,    0,
      356,  357,  357,  357,    0,  357,  358,    0,  358,  358,
      359,    0,  359,  359,  360,  360,    0,  360,  361,  361,
      361,    0,  361,  362,  362,  362,    0,  362,  363,  363,
      363,    0,  363,  364,  364,  364,    0,  364,  365,  365,
      365,  366,  366,  366,    0,  366,  367,  367,  367,    0,
      367,  368,  368,  368,  368,  368,  369,  369,    0,  369,
      370,  370,  370,    0,  370,  371,  371,  371,    0,  371,

      372,  372,  372,    0,  372,  373,  373,  373,    0,  373,
      374,  374,  374,    0,  374,  375,  375,  375,  375,  376,
      376,  376,    0,  376,  377,  377,  377,    0,  377,  378,
      378,  378,    0,  378,  379,  379,  379,    0,  379,  380,
      380,  380,  380,  380,  381,  381,  381,    0,  381,  382,
      382,  382,    0,  382,  383,  383,  383,    0,  383,  384,
      384,  384,    0,  384,  385,  385,  385,    0,  385,  386,
      386,  386,    0,  386,  387,  387,  387,    0,  387,  388,
      388,  388,  388,  389,  389,  389,    0,  389,  390,  390,
      390,    0,  390,  391,  391,  391,    0,  391,  392,  392,

      392,    0,  392,  393,  393,  393,  393,  393,  394,  394,
      394,    0,  394,  395,  395,  395,    0,  395,  396,  396,
      396,    0,  396,  397,  397,  397,    0,  397,  398,  398,
      398,    0,  398,  399,  399,  399,    0,  399,  400,  400,
      400,    0,  400,  401,  401,  401,  401,  402,  402,  402,
        0,  402,  403,  403,  403,    0,  403,  404,  404,  404,
        0,  404,  405,  405,  405,    0,  405,  406,  406,  406,
        0,  406,  407,  407,  407,    0,  407,  408,  408,  408,
        0,  408,  409,  409,  409,  409,  409,  410,  410,  410,
        0,  410,  411,  411,  411,    0,  411,  412,  412,  412,

        0,  412,  413,  413,  413,    0,  413,  414,  414,  414,
        0,  414,  415,  415,  415,    0,  415,  416,  416,  416,
        0,  416,  417,  417,  417,    0,  417,  418,  418,  418,
        0,  418,  419,  419,  419,    0,  419,  420,  420,  420,
      420,  421,  421,  421,    0,  421,  422,  422,  422,    0,
      422,  423,  423,  423,    0,  423,  424,  424,  424,    0,
      424,  425,  425,  425,    0,  425,  426,  426,  426,    0,
      426,  427,  427,  427,  427,  427,  428,  428,  428,    0,
      428,  429,  429,  429,    0,  429,  430,  430,  430,    0,
      430,  431,  431,  431,    0,  431,  432,  432,  432,    0,

      432,  433,  433,  433,    0,  433,  434,  434,  434,    0,
      434,  435,  435,  435,    0,  435,  436,  436,  436,    0,
      436,  437,  437,  437,    0,  437,  438,  438,  438,  438,
      439,  439,  439,    0,  439,  440,  440,  440,    0,  440,
      441,  441,  441,    0,  441,  442,  442,  442,    0,  442,
      443,  443,  443,    0,  443,  444,  444,  444,    0,  444,
      445,  445,  445,    0,  445,  446,  446,  446,    0,  446,
      447,  447,  447,  447,  447,  448,  448,  448,    0,  448,
      449,  449,  449,    0,  449,  450,  450,  450,    0,  450,
      451,  451,  451,    0,  451,  452,  452,  452,    0,  452,

      453,  453,  453,    0,  453,  454,  454,  454,    0,  454,
      455,  455,  455,    0,  455,  456,  456,  456,    0,  456,
      457,  457,  457,    0,  457,  458,  458,  458,  458,  459,
      459,  459,    0,  459,  460,  460,  460,    0,  460,  461,
      461,  461,    0,  461,  462,  462,  462,    0,  462,  463,
      463,  463,    0,  463,  464,  464,  464,    0,  464,  465,
      465,  465,    0,  465,  466,  466,  466,    0,  466,  467,
      467,  467,  467,  467,  468,  468,  468,    0,  468,  469,
      469,  469,    0,  469,  470,  470,  470,    0,  470,  471,
      471,  471,    0,  471,  472,  472,  472,    0,  472,  473,

      473,  473,    0,  473,  474,  474,  474,    0,  474,  475,
      475,  475,    0,  475,  476,  476,  476,    0,  476,  477,
      477,  477,    0,  477,  478,  478,  478,    0,  478,  479,
      479,  479,  479,  480,  480,  480,    0,  480,  481,  481,
      481,    0,  481,  482,  482,  482,    0,  482,  483,  483,
      483,  483,  483,  484,  484,  484,    0,  484,  485,  485,
      485,    0,  485,  486,  486,  486,    0,  486,  487,  487,
      487,    0,  487,  488,  488,  488,    0,  488,  489,  489,
      489,  489,  489,  490,  490,  490,  490,  490,  491,  491,
      491,  491,  491,  492,  492,  492,  492,  492,  493,  493,

      493,  493,  493,  494,  494,  494,  494,  494,  495,  495,
      495,  495,  495,  496,  496,  496,  496,  496,  497,  497,
      497,  497,  497,  498,  498,  498,  498,  498,  499,  499,
      499,  499,  499,  500,  500,  500,  500,  500,  501,  501,
      501,  501,  501,  502,  502,  502,  502,  502,  503,  503,
      503,  503,  503,  504,  504,  504,  504,  504,  505,  505,
      505,  505,  505,  506,  506,  506,  506,  506,  507,  507,
      507,  507,  507,  508,  508,  508,  508,  508,  509,  509,
      509,  509,  509,  510,  510,  510,  510,  510,  511,  511,
      511,  511,  511,  512,  512,  512,  512,  512,  513,  513,

      513,  513,  513,  514,  514,  514,  514,  514,  515,  515,
      515,  515,  515,  516,  516,  516,  516,  516,  517,  517,
      517,  517,  517,  518,  518,  518,  518,  518,  519,  519,
      519,  519,  519,  520,  520,  520,  520,  520,  521,  521,
      521,  521,  521,  522,  522,  522,  522,  522,  523,  523,
      523,  523,  523,  524,  524,  524,  524,  524,  525,  525,
      525,  525,  525,  526,  526,  526,  526,  526,  527,  527,
      527,  527,  527,  528,  528,  528,  528,  528,  529,  529,
      529,  529,  529,  530,  530,  530,  530,  530,  531,  531,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[35] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
#line 5 "lexical.l"
	#include "syntax.tab.h"
	#include <string.h>
	#include <stdlib.h>
	//#include "gtree.h"
	#define SYNTAX

	extern int is_error;
	int yycolumn = 1;
	#define YY_USER_ACTION {\
		yylloc.first_line = yylloc.last_line = yylineno; \
		yylloc.first_column = yycolumn; \
		yylloc.last_column = yycolumn + yyleng - 1; \
		yycolumn += yyleng;	\
	}
	extern void yyerror(const char* s);
	//#define LEX
#line 1179 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 86 "lexical.l"

#line 1399 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 350 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2291 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("STRUCT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return STRUCT;
	#endif
	/*~!@#$%%^&*()_+`-=[]\{}|;':",./<>?*/
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RETURN", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RETURN;
	#endif
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("IF", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return IF;
	#endif
	return IF;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 116 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("ELSE", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return ELSE;
	#endif	
	return  ELSE;	
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 126 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("WHILE", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return WHILE;
	#endif
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 135 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mint\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	int num = 0;
	if(yytext[0] == '0' && (yytext[1] == 'x'||yytext[1] == 'X'))
		num = HextoDec(yytext);
	else if(yytext[0] == '0')
		num = OcttoDec(yytext);
	else
		num = atoi(yytext);
	yylval.gnode = CreateIntGNode(num, yylineno);
	#ifdef SYNTAX	
		return INT;
	#endif
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 151 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mtype\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateTypeGNode(yytext, yylineno);
	#ifdef SYNTAX	
		return TYPE;
	#endif
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 160 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mfloat\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateFloatGNode(atof(yytext), yylineno);
	#ifdef SYNTAX	
		return FLOAT;
	#endif
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 169 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mid\033[0m at line \033[45;37m%d \033[0m\n", yylineno);
	#endif
	yylval.gnode = CreateIdGNode(yytext, yylineno);
	#ifdef SYNTAX	
		return ID;
	#endif
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 178 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("SEMI", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return SEMI;
	#endif		
	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 187 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("COMMA", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return COMMA;
	#endif
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 196 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("ASSIGNOP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return ASSIGNOP;
	#endif	
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 205 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateRelopGNode(yylineno, yytext);
	#ifdef SYNTAX	
		return RELOP;
	#endif
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 214 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("PLUS", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return PLUS;
	#endif		
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 223 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("MINUS", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return MINUS;
	#endif
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 232 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("STAR", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return STAR;
	#endif
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 241 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("DIV", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return DIV;
	#endif
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 250 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("AND", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return AND;
	#endif	
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 259 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("OR", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return OR;
	#endif
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 268 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("DOT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return DOT;
	#endif	
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 277 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("NOT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return NOT;
	#endif
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 286 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LP;
	#endif
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 295 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RP;
	#endif
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 304 "lexical.l"
{	
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LB", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LB;
	#endif	
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 313 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RB", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RB;
	#endif
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 322 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LC", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LC;
	#endif	
	}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 331 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RC", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RC;
	#endif
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 340 "lexical.l"
{
	char c = input();
	while (c != '\n') 
		c = input();
	#ifdef LEX
	printf("this is \033[42;35mpre-process parts\033[0m in line \033[42;37m%d\033[0m\n", yylineno-1);
	#endif
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 348 "lexical.l"
{ yycolumn = 1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 349 "lexical.l"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 350 "lexical.l"
{
	char c = input();
	while (1) {
		c = input();
		if(c == '\n')
			break;
		if(c == -1) {
			#ifdef LEX
			printf("in the end\n");
			#endif
			yyerror("SYNTAX ERROR");
			break;
		}
	}
	#ifdef LEX
	printf("\033[42;35mthis is //annotation\033[0m\n");
	#endif
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 368 "lexical.l"
{
	char c1 = input();
	while (1) {
		//printf("c1c2: %c%c %d %d\n", c1, c2, c1, c2);
		if((c1=='*')){
			char c2 = input();
			if(c2 == '/') {
				#ifdef LEX
				printf("\033[42;35mthis is /**/annotation\033[0m\n");
				#endif
				break;
			}
		}
		if(c1 == -1) {
			#ifdef LEX
			printf("this is read end\n");
			#endif
			is_error = 1;
			yyerror("SYNTAX ERROR");
			break;
		}	
		c1 = input();
	}
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 392 "lexical.l"
{
		is_error = 1;
		//printf("\033[45;37mError type A at Line %d: Mysterious characters \'%s\'\033[0m\n", yylineno, yytext);
		printf("Error type A at Line %d: Mysterious characters \'%s\'.\n", yylineno, yytext);
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 399 "lexical.l"
ECHO;
	YY_BREAK
#line 1914 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 350 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 350 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 349);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 399 "lexical.l"




