
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[280] =
    {   0,
       30,   30,   35,   33,   30,   29,   30,   21,   28,   33,
       22,   23,   16,   14,   11,   15,   20,   17,    6,    6,
        6,    6,   10,   13,   12,   13,    9,    9,   24,   25,
        9,    9,    9,    9,    9,    9,   26,   33,   27,   30,
       13,   18,    0,    0,   32,   31,    0,    0,    6,    6,
        6,    0,    6,    6,    6,    6,    9,    0,    8,    9,
        9,    3,    9,    9,    9,    9,   19,    8,    8,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    9,    8,
        9,    9,    7,    9,    9,    9,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    9,    8,    4,    9,

        9,    9,    9,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    9,    8,    7,    9,    9,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    9,    8,    2,    1,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    9,
        8,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    9,    8,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    9,    8,    6,    6,    6,    6,    6,    9,
        8,    6,    6,    6,    9,    8,    9,    8,    9,    8,

        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    9,    8,    9,    8,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,    1,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,    1,   35,    1,   32,    1,   36,   30,   37,   30,

       38,   39,   32,   40,   41,   32,   32,   42,   32,   43,
       44,   32,   32,   45,   46,   47,   48,   32,   49,   50,
       32,   32,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    2,    3,    1,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    6,
        7,    8,    8,    1,    1,    6,    6,    7,    6,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[414] =
    {   0,
        0,    0,  238, 1785, 1785, 1785,  233,  208, 1785,  227,
     1785, 1785, 1785, 1785, 1785, 1785,   23,   45,   48,   44,
       71,   45, 1785,  204,  203,  202,    0,   99, 1785, 1785,
      187,  167,   35,  166,  156,  162, 1785,  145, 1785,  192,
     1785, 1785,   25,   78, 1785, 1785,   46,   66,   76,  111,
      113,    0,  112,  114,  139,   76,    0,   92,  162,  149,
      150,    0,  145,  129,  130,  133, 1785,    0,   68,  116,
      174,  176,    0,  134,  175,  177,  202,  179,    0,  225,
      135,  135,    0,  121,  120,  104,  237,  239,  241,    0,
      197,  238,  240,  242,  267,  277,    0,  290,    0,   92,

       84,   76,   73,  302,  304,  306,    0,  286,  305,  307,
      308,  318,  327,  333,    0,  356,    0,   65,   10,    0,
      368,  370,  372,    0,  352,  371,  373,  374,  384,  386,
      411,  115,    0,  434,    0,    0,  446,  448,  450,    0,
      406,  407,  409,  447,  449,  451,  452,  477,  478,    0,
      501,  513,  515,  517,    0,  497,  516,  518,  519,  529,
      531,  544,  545,  570,  343,    0,  593,  547,  605,  607,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  565,
      142,  566,    0,  630,  642,  644,  646, 1785,  567,    0,
      669,  681,    0,    0,    0,  704,    0,  714,    0,  724,

        0,  734,    0,  744,    0,  754,    0,  764,    0,  774,
        0,  784,    0,  794,    0,  804,    0,  814,    0,  824,
        0,  834,    0,  844,    0,  854,    0,  864,    0,  874,
        0,  884,    0,  894,    0,  904,    0,  914,    0,  924,
        0,  934,    0,  944,    0,  954,    0,  964,    0,  974,
        0,  984,    0,  994,    0, 1004,    0, 1014,    0, 1024,
        0, 1034,    0, 1044,    0, 1054,    0, 1064,    0, 1074,
        0, 1084,    0, 1094,    0, 1104, 1785,    0, 1785, 1126,
     1131, 1136, 1140, 1147, 1149, 1154, 1159, 1164, 1169, 1172,
     1177, 1182, 1186, 1192, 1197, 1202, 1206, 1211, 1216, 1221,

     1226, 1230, 1236, 1241, 1246, 1250, 1255, 1260, 1265, 1270,
     1274, 1280, 1285, 1290, 1294, 1299, 1304, 1309, 1314, 1319,
     1324, 1329, 1333, 1339, 1344, 1349, 1353, 1358, 1363, 1368,
     1373, 1378, 1383, 1387, 1393, 1398, 1403, 1407, 1412, 1417,
     1422, 1427, 1432, 1437, 1442, 1447, 1451, 1457, 1462, 1467,
     1471, 1476, 1481, 1486, 1491, 1496, 1501, 1506, 1511, 1515,
     1521, 1526, 1531, 1535, 1540, 1545, 1549, 1555, 1560, 1565,
     1569, 1574, 1579, 1584, 1589, 1594, 1599, 1604, 1609, 1614,
     1619, 1624, 1629, 1634, 1639, 1644, 1649, 1654, 1659, 1664,
     1669, 1674, 1679, 1684, 1689, 1694, 1699, 1704, 1709, 1714,

     1719, 1724, 1729, 1734, 1739, 1744, 1749, 1754, 1759, 1764,
     1769, 1774, 1779
    } ;

static yyconst flex_int16_t yy_def[414] =
    {   0,
      279,    1,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  280,  279,  279,  281,
      282,  282,  279,  279,  279,  279,  283,  283,  279,  279,
       28,  283,  283,  283,  283,  283,  279,  279,  279,  279,
      279,  279,  280,  284,  279,  279,  285,  286,  287,  288,
      289,  290,  291,  292,  279,   55,  293,  284,  293,  293,
      293,  293,  293,  293,  293,  293,  279,   58,  285,  294,
      295,  296,  297,  298,  299,  300,  279,  301,  302,  302,
      302,  302,  302,  302,  302,  302,  303,  304,  305,  306,
      307,  308,  309,  310,  279,   95,  311,  311,  311,  311,

      311,  311,  311,  312,  313,  314,  315,  316,  317,  318,
      319,  320,  321,  322,  323,  323,  323,  323,  323,  323,
      324,  325,  326,  327,  328,  329,  330,  331,  332,  333,
      279,  131,  334,  334,  334,  334,  335,  336,  337,  338,
      339,  340,  341,  342,  343,  344,  345,  279,  346,  347,
      347,  348,  349,  350,  351,  352,  353,  354,  355,  356,
      357,  358,  359,  279,  164,  360,  360,  361,  362,  363,
      364,  165,  165,  165,  165,  165,  165,  165,  165,  365,
      165,  366,  367,  367,  368,  369,  370,  279,  366,  371,
      371,  370,  192,  189,  372,  372,  373,  373,  374,  374,

      375,  375,  376,  376,  377,  377,  378,  378,  379,  379,
      380,  380,  381,  381,  382,  382,  383,  383,  384,  384,
      385,  385,  386,  386,  387,  387,  388,  388,  389,  389,
      390,  390,  391,  391,  392,  392,  393,  393,  394,  394,
      395,  395,  396,  396,  397,  397,  398,  398,  399,  399,
      400,  400,  401,  401,  402,  402,  403,  403,  404,  404,
      405,  405,  406,  406,  407,  407,  408,  408,  409,  409,
      410,  410,  411,  411,  412,  412,  279,  413,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279
    } ;

static yyconst flex_uint16_t yy_nxt[1839] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   27,   27,   29,   30,   27,   27,   31,   32,   27,
       33,   27,   27,   27,   34,   35,   27,   27,   36,   27,
       37,   38,   39,   44,   45,   44,  136,   47,   47,   46,
       44,   47,   44,   48,   49,   50,   50,   51,   51,   51,
       51,   48,   48,   62,   44,   44,   44,   63,   44,   47,
       52,   44,   44,   44,   47,   44,   54,   55,   58,   47,
       58,   78,   78,   78,   78,   78,   44,   52,   44,   48,

       48,   44,  279,   44,  279,   44,   44,  135,   44,   58,
      120,   58,  119,   44,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   47,   47,   47,   47,  118,   47,
      149,  149,  149,  149,   48,   48,   48,   48,  117,   48,
       48,   44,   44,   44,   44,  103,   44,   47,   44,   44,
       44,   44,   47,   44,   76,   76,   76,   76,   77,   78,
       78,   78,   78,   78,   44,   48,   48,  102,  101,   44,
      100,   44,   99,   86,   85,   84,   44,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   47,   47,   47,
       47,   83,   47,   82,   81,   40,   67,   48,   48,   48,

       48,   66,   65,   64,   44,   44,   44,   44,   61,   44,
       47,   44,   44,   44,   44,   47,   44,   94,   94,   94,
       94,   94,   94,   94,   95,   96,   96,   44,   60,   41,
       41,   41,   44,   42,   44,   41,   40,  279,  279,   44,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       47,   47,   47,   47,   47,   47,  279,  279,  279,  279,
       48,   48,   48,   48,   48,   48,  279,   44,   44,   44,
       44,   44,   44,  279,   44,   44,   44,   44,   44,   44,
       47,  279,  112,  112,  112,  112,  113,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,   44,  279,   47,

      279,  279,  279,  279,   44,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,   47,   44,   47,   47,   47,
       47,   47,  279,   44,  279,   48,   48,   48,   48,   48,
       48,   47,   44,  279,   44,   44,   44,   44,   44,   44,
       47,   44,   44,   44,   44,   44,   47,  279,   44,  279,
      131,  132,  279,  279,  279,   44,  279,   44,  182,  182,
      182,  182,  182,   44,   44,   47,  279,  279,  279,  279,
       44,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,   47,   44,   47,   47,   47,   47,   47,  279,   44,
      279,   48,   48,   48,   48,   48,   48,   47,   44,   47,

       44,   44,   44,   44,   44,   44,  279,   44,   44,   44,
       44,   44,  279,  279,   44,  279,   44,  279,  279,   47,
       47,   44,   47,   44,   47,  279,  147,  147,  147,  148,
      149,  149,  149,  149,  149,  149,   44,   44,  279,   44,
      279,   44,  279,   44,   44,  279,   44,  279,   44,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,   47,
       47,   47,   47,   47,   47,   47,  279,  279,  279,   48,
       48,   48,   48,   48,   48,  279,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       47,   47,  163,  163,  163,  163,  163,  163,  164,  165,

      165,  165,  279,  279,  279,  279,  279,   44,   44,  279,
       47,  279,  279,  279,   44,   44,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,   47,   44,   47,   47,
       47,   47,   47,  279,   44,  279,   48,   48,   48,   48,
       48,   48,   47,   44,   47,   44,   44,   44,   44,   44,
       44,  279,   44,   44,   44,   44,   44,   47,   47,   44,
       47,   44,  279,  279,  279,  279,   44,  279,   44,  279,
       48,   48,  279,  279,   44,   44,  279,   44,   47,   47,
       47,   44,   44,   47,   44,  180,  180,  180,  180,  181,
      182,  182,  182,  182,  182,   44,   44,   44,  279,  279,

       44,  279,   44,   44,   44,  279,  279,   44,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,   47,  279,
       47,  279,  279,  279,  279,  279,  279,  279,   48,   48,
       48,   48,  279,  279,  279,   44,  279,   44,  279,  279,
      279,  279,   44,  279,   44,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,   47,  279,   47,  279,   47,
      279,  279,  279,  279,  279,   48,   48,   48,   48,   48,
       48,  279,   44,  279,   44,  279,   44,  279,  279,   44,
      279,   44,  279,   44,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,   47,  279,  279,  279,  279,  279,

      279,  279,  279,  279,   48,   48,  279,  279,  279,  279,
      279,   44,  279,  279,  279,  279,  279,  279,   44,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  214,

      214,  214,  214,  214,  214,  214,  214,  214,  214,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  234,

      234,  234,  234,  234,  234,  234,  234,  234,  234,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,   43,
       43,  279,   43,   53,   53,   53,  279,   53,   56,   56,
       56,  279,   56,   57,   57,   57,   57,   57,   68,  279,
       68,   68,   69,   69,  279,   69,   48,   48,   48,  279,
       48,   70,   70,   70,  279,   70,   71,   71,   71,  279,
       71,   72,   72,   72,  279,   72,   73,   73,   73,   74,
       74,   74,  279,   74,   75,   75,   75,  279,   75,   79,
       79,   79,   79,   79,   87,   87,   87,  279,   87,   88,

       88,   88,  279,   88,   89,   89,   89,  279,   89,   90,
       90,   90,   90,   91,   91,   91,  279,   91,   92,   92,
       92,  279,   92,   93,   93,   93,  279,   93,   96,   96,
       96,  279,   96,   97,   97,   97,   97,   97,  104,  104,
      104,  279,  104,  105,  105,  105,  279,  105,  106,  106,
      106,  279,  106,  107,  107,  107,  107,  108,  108,  108,
      279,  108,  109,  109,  109,  279,  109,  110,  110,  110,
      279,  110,  111,  111,  111,  279,  111,  115,  115,  115,
      115,  115,  121,  121,  121,  279,  121,  122,  122,  122,
      279,  122,  123,  123,  123,  279,  123,  124,  124,  124,

      124,  125,  125,  125,  279,  125,  126,  126,  126,  279,
      126,  127,  127,  127,  279,  127,  128,  128,  128,  279,
      128,  129,  129,  129,  279,  129,  130,  130,  130,  279,
      130,  132,  132,  132,  279,  132,  133,  133,  133,  133,
      133,  137,  137,  137,  279,  137,  138,  138,  138,  279,
      138,  139,  139,  139,  279,  139,  140,  140,  140,  140,
      141,  141,  141,  279,  141,  142,  142,  142,  279,  142,
      143,  143,  143,  279,  143,  144,  144,  144,  279,  144,
      145,  145,  145,  279,  145,  146,  146,  146,  279,  146,
      150,  150,  150,  150,  150,  152,  152,  152,  279,  152,

      153,  153,  153,  279,  153,  154,  154,  154,  279,  154,
      155,  155,  155,  155,  156,  156,  156,  279,  156,  157,
      157,  157,  279,  157,  158,  158,  158,  279,  158,  159,
      159,  159,  279,  159,  160,  160,  160,  279,  160,  161,
      161,  161,  279,  161,  162,  162,  162,  279,  162,  165,
      165,  165,  279,  165,  166,  166,  166,  166,  166,  168,
      168,  168,  279,  168,  169,  169,  169,  279,  169,  170,
      170,  170,  279,  170,  171,  171,  171,  171,  172,  172,
      172,  279,  172,  173,  173,  173,  279,  173,  174,  174,
      174,  279,  174,  175,  175,  175,  279,  175,  176,  176,

      176,  279,  176,  177,  177,  177,  279,  177,  178,  178,
      178,  279,  178,  179,  179,  179,  279,  179,  183,  183,
      183,  183,  183,  185,  185,  185,  279,  185,  186,  186,
      186,  279,  186,  187,  187,  187,  279,  187,  188,  188,
      188,  188,  189,  189,  189,  279,  189,   48,   48,   48,
      279,   48,  190,  190,  190,  190,  190,  192,  192,  192,
      279,  192,  193,  193,  193,  279,  193,  194,  194,  194,
      279,  194,  195,  195,  195,  195,  195,  197,  197,  197,
      197,  197,  199,  199,  199,  199,  199,  201,  201,  201,
      201,  201,  203,  203,  203,  203,  203,  205,  205,  205,

      205,  205,  207,  207,  207,  207,  207,  209,  209,  209,
      209,  209,  211,  211,  211,  211,  211,  213,  213,  213,
      213,  213,  215,  215,  215,  215,  215,  217,  217,  217,
      217,  217,  219,  219,  219,  219,  219,  221,  221,  221,
      221,  221,  223,  223,  223,  223,  223,  225,  225,  225,
      225,  225,  227,  227,  227,  227,  227,  229,  229,  229,
      229,  229,  231,  231,  231,  231,  231,  233,  233,  233,
      233,  233,  235,  235,  235,  235,  235,  237,  237,  237,
      237,  237,  239,  239,  239,  239,  239,  241,  241,  241,
      241,  241,  243,  243,  243,  243,  243,  245,  245,  245,

      245,  245,  247,  247,  247,  247,  247,  249,  249,  249,
      249,  249,  251,  251,  251,  251,  251,  253,  253,  253,
      253,  253,  255,  255,  255,  255,  255,  257,  257,  257,
      257,  257,  259,  259,  259,  259,  259,  261,  261,  261,
      261,  261,  263,  263,  263,  263,  263,  265,  265,  265,
      265,  265,  267,  267,  267,  267,  267,  269,  269,  269,
      269,  269,  271,  271,  271,  271,  271,  273,  273,  273,
      273,  273,  275,  275,  275,  275,  275,  277,  277,  277,
      277,  277,   68,   68,    3,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279
    } ;

static yyconst flex_int16_t yy_chk[1839] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   17,   18,   43,  119,   20,   22,   18,
       17,   19,   43,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   33,   20,   22,   47,   33,   19,   48,
       19,   20,   22,   47,   21,   19,   21,   21,   44,   49,
       44,   56,   56,   56,   56,   56,   48,   19,   69,   49,

       49,   21,   58,   48,   58,   69,   49,  118,   21,   28,
      103,   28,  102,   49,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   50,   53,   51,   54,  101,   70,
      132,  132,  132,  132,   50,   50,   51,   51,  100,   70,
       70,   50,   53,   51,   54,   86,   70,   74,   50,   53,
       51,   54,   55,   70,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   74,  181,  181,   85,   84,   55,
       82,   74,   81,   66,   65,   64,   55,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   71,   75,   72,
       76,   63,   78,   61,   60,   40,   38,   71,   71,   72,

       72,   36,   35,   34,   71,   75,   72,   76,   32,   78,
       91,   71,   75,   72,   76,   77,   78,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   91,   31,   26,
       25,   24,   77,   10,   91,    8,    7,    3,    0,   77,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       87,   92,   88,   93,   89,   94,    0,    0,    0,    0,
       87,   87,   88,   88,   89,   89,    0,   87,   92,   88,
       93,   89,   94,    0,   87,   92,   88,   93,   89,   94,
       95,    0,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   96,   96,   96,   96,   96,   95,    0,  108,

        0,    0,    0,    0,   95,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,  104,  108,  105,  109,  106,
      110,  111,    0,  108,    0,  104,  104,  105,  105,  106,
      106,  112,  104,    0,  105,  109,  106,  110,  111,  104,
      113,  105,  109,  106,  110,  111,  114,    0,  112,    0,
      113,  113,    0,    0,    0,  112,    0,  113,  165,  165,
      165,  165,  165,  114,  113,  125,    0,    0,    0,    0,
      114,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  121,  125,  122,  126,  123,  127,  128,    0,  125,
        0,  121,  121,  122,  122,  123,  123,  129,  121,  130,

      122,  126,  123,  127,  128,  121,    0,  122,  126,  123,
      127,  128,    0,    0,  129,    0,  130,    0,    0,  141,
      142,  129,  143,  130,  131,    0,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  141,  142,    0,  143,
        0,  131,    0,  141,  142,    0,  143,    0,  131,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  137,
      144,  138,  145,  139,  146,  147,    0,    0,    0,  137,
      137,  138,  138,  139,  139,    0,  137,  144,  138,  145,
      139,  146,  147,  137,  144,  138,  145,  139,  146,  147,
      148,  149,  148,  148,  148,  148,  148,  148,  148,  148,

      148,  148,    0,    0,    0,    0,    0,  148,  149,    0,
      156,    0,    0,    0,  148,  149,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  152,  156,  153,  157,
      154,  158,  159,    0,  156,    0,  152,  152,  153,  153,
      154,  154,  160,  152,  161,  153,  157,  154,  158,  159,
      152,    0,  153,  157,  154,  158,  159,  162,  163,  160,
      168,  161,    0,    0,    0,    0,  160,    0,  161,    0,
      168,  168,    0,    0,  162,  163,    0,  168,  180,  182,
      189,  162,  163,  164,  168,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  180,  182,  189,    0,    0,

      164,    0,  180,  182,  189,    0,    0,  164,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  169,    0,
      170,    0,    0,    0,    0,    0,    0,    0,  169,  169,
      170,  170,    0,    0,    0,  169,    0,  170,    0,    0,
        0,    0,  169,    0,  170,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  185,    0,  186,    0,  187,
        0,    0,    0,    0,    0,  185,  185,  186,  186,  187,
      187,    0,  185,    0,  186,    0,  187,    0,    0,  185,
        0,  186,    0,  187,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  192,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  192,  192,    0,    0,    0,    0,
        0,  192,    0,    0,    0,    0,    0,    0,  192,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  280,
      280,    0,  280,  281,  281,  281,    0,  281,  282,  282,
      282,    0,  282,  283,  283,  283,  283,  283,  284,    0,
      284,  284,  285,  285,    0,  285,  286,  286,  286,    0,
      286,  287,  287,  287,    0,  287,  288,  288,  288,    0,
      288,  289,  289,  289,    0,  289,  290,  290,  290,  291,
      291,  291,    0,  291,  292,  292,  292,    0,  292,  293,
      293,  293,  293,  293,  294,  294,  294,    0,  294,  295,

      295,  295,    0,  295,  296,  296,  296,    0,  296,  297,
      297,  297,  297,  298,  298,  298,    0,  298,  299,  299,
      299,    0,  299,  300,  300,  300,    0,  300,  301,  301,
      301,    0,  301,  302,  302,  302,  302,  302,  303,  303,
      303,    0,  303,  304,  304,  304,    0,  304,  305,  305,
      305,    0,  305,  306,  306,  306,  306,  307,  307,  307,
        0,  307,  308,  308,  308,    0,  308,  309,  309,  309,
        0,  309,  310,  310,  310,    0,  310,  311,  311,  311,
      311,  311,  312,  312,  312,    0,  312,  313,  313,  313,
        0,  313,  314,  314,  314,    0,  314,  315,  315,  315,

      315,  316,  316,  316,    0,  316,  317,  317,  317,    0,
      317,  318,  318,  318,    0,  318,  319,  319,  319,    0,
      319,  320,  320,  320,    0,  320,  321,  321,  321,    0,
      321,  322,  322,  322,    0,  322,  323,  323,  323,  323,
      323,  324,  324,  324,    0,  324,  325,  325,  325,    0,
      325,  326,  326,  326,    0,  326,  327,  327,  327,  327,
      328,  328,  328,    0,  328,  329,  329,  329,    0,  329,
      330,  330,  330,    0,  330,  331,  331,  331,    0,  331,
      332,  332,  332,    0,  332,  333,  333,  333,    0,  333,
      334,  334,  334,  334,  334,  335,  335,  335,    0,  335,

      336,  336,  336,    0,  336,  337,  337,  337,    0,  337,
      338,  338,  338,  338,  339,  339,  339,    0,  339,  340,
      340,  340,    0,  340,  341,  341,  341,    0,  341,  342,
      342,  342,    0,  342,  343,  343,  343,    0,  343,  344,
      344,  344,    0,  344,  345,  345,  345,    0,  345,  346,
      346,  346,    0,  346,  347,  347,  347,  347,  347,  348,
      348,  348,    0,  348,  349,  349,  349,    0,  349,  350,
      350,  350,    0,  350,  351,  351,  351,  351,  352,  352,
      352,    0,  352,  353,  353,  353,    0,  353,  354,  354,
      354,    0,  354,  355,  355,  355,    0,  355,  356,  356,

      356,    0,  356,  357,  357,  357,    0,  357,  358,  358,
      358,    0,  358,  359,  359,  359,    0,  359,  360,  360,
      360,  360,  360,  361,  361,  361,    0,  361,  362,  362,
      362,    0,  362,  363,  363,  363,    0,  363,  364,  364,
      364,  364,  365,  365,  365,    0,  365,  366,  366,  366,
        0,  366,  367,  367,  367,  367,  367,  368,  368,  368,
        0,  368,  369,  369,  369,    0,  369,  370,  370,  370,
        0,  370,  371,  371,  371,  371,  371,  372,  372,  372,
      372,  372,  373,  373,  373,  373,  373,  374,  374,  374,
      374,  374,  375,  375,  375,  375,  375,  376,  376,  376,

      376,  376,  377,  377,  377,  377,  377,  378,  378,  378,
      378,  378,  379,  379,  379,  379,  379,  380,  380,  380,
      380,  380,  381,  381,  381,  381,  381,  382,  382,  382,
      382,  382,  383,  383,  383,  383,  383,  384,  384,  384,
      384,  384,  385,  385,  385,  385,  385,  386,  386,  386,
      386,  386,  387,  387,  387,  387,  387,  388,  388,  388,
      388,  388,  389,  389,  389,  389,  389,  390,  390,  390,
      390,  390,  391,  391,  391,  391,  391,  392,  392,  392,
      392,  392,  393,  393,  393,  393,  393,  394,  394,  394,
      394,  394,  395,  395,  395,  395,  395,  396,  396,  396,

      396,  396,  397,  397,  397,  397,  397,  398,  398,  398,
      398,  398,  399,  399,  399,  399,  399,  400,  400,  400,
      400,  400,  401,  401,  401,  401,  401,  402,  402,  402,
      402,  402,  403,  403,  403,  403,  403,  404,  404,  404,
      404,  404,  405,  405,  405,  405,  405,  406,  406,  406,
      406,  406,  407,  407,  407,  407,  407,  408,  408,  408,
      408,  408,  409,  409,  409,  409,  409,  410,  410,  410,
      410,  410,  411,  411,  411,  411,  411,  412,  412,  412,
      412,  412,  413,  413,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[35] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
#line 5 "lexical.l"
	#include "syntax.tab.h"
	#include <string.h>
	#include <stdlib.h>
	//#include "gtree.h"
	#define SYNTAX

	extern int is_error;
	int yycolumn = 1;
	#define YY_USER_ACTION {\
		yylloc.first_line = yylloc.last_line = yylineno; \
		yylloc.first_column = yycolumn; \
		yylloc.last_column = yycolumn + yyleng - 1; \
		yycolumn += yyleng;	\
	}
	extern void yyerror(const char* s);
	//#define LEX
#line 1033 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 86 "lexical.l"

#line 1253 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1785 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("STRUCT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return STRUCT;
	#endif
	/*~!@#$%%^&*()_+`-=[]\{}|;':",./<>?*/
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RETURN", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RETURN;
	#endif
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("IF", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return IF;
	#endif
	return IF;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 116 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("ELSE", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return ELSE;
	#endif	
	return  ELSE;	
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 126 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mkeyword\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("WHILE", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return WHILE;
	#endif
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 135 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mint\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	int num = 0;
	if(yytext[0] == '0' && (yytext[1] == 'x'||yytext[1] == 'X'))
		num = HextoDec(yytext);
	else if(yytext[0] == '0')
		num = OcttoDec(yytext);
	else
		num = atoi(yytext);
	yylval.gnode = CreateIntGNode(num, yylineno);
	#ifdef SYNTAX	
		return INT;
	#endif
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 151 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mtype\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateTypeGNode(yytext, yylineno);
	#ifdef SYNTAX	
		return TYPE;
	#endif
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 160 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mfloat\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateFloatGNode(atof(yytext), yylineno);
	#ifdef SYNTAX	
		return FLOAT;
	#endif
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 169 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30mid: %s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateIdGNode(yytext, yylineno);
	#ifdef SYNTAX	
		return ID;
	#endif
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 178 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("SEMI", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return SEMI;
	#endif		
	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 187 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("COMMA", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return COMMA;
	#endif
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 196 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("ASSIGNOP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return ASSIGNOP;
	#endif	
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 205 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateRelopGNode(yylineno, yytext);
	#ifdef SYNTAX	
		return RELOP;
	#endif
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 214 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("PLUS", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return PLUS;
	#endif		
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 223 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("MINUS", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return MINUS;
	#endif
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 232 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("STAR", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return STAR;
	#endif
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 241 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("DIV", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return DIV;
	#endif
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 250 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("AND", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return AND;
	#endif	
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 259 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("OR", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return OR;
	#endif
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 268 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("DOT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return DOT;
	#endif	
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 277 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("NOT", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return NOT;
	#endif
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 286 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LP;
	#endif
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 295 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RP", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RP;
	#endif
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 304 "lexical.l"
{	
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LB", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LB;
	#endif	
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 313 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RB", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RB;
	#endif
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 322 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("LC", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return LC;
	#endif	
	}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 331 "lexical.l"
{
	#ifdef LEX
	printf("this is \033[47;30msymbol\033[0m \033[46;37m%s\033[0m at line \033[45;37m%d \033[0m\n", yytext, yylineno);
	#endif
	yylval.gnode = CreateGNode("RC", yylineno, _INIT_, Terminal, 0);
	#ifdef SYNTAX	
		return RC;
	#endif
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 340 "lexical.l"
{
	char c = input();
	while (c != '\n') 
		c = input();
	#ifdef LEX
	printf("this is \033[42;35mpre-process parts\033[0m in line \033[42;37m%d\033[0m\n", yylineno-1);
	#endif
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 348 "lexical.l"
{ yycolumn = 1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 349 "lexical.l"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 350 "lexical.l"
{
	char c = input();
	while (1) {
		c = input();
		if(c == '\n')
			break;
		if(c == -1) {
			#ifdef LEX
			printf("in the end\n");
			#endif
			yyerror("SYNTAX ERROR");
			break;
		}
	}
	#ifdef LEX
	printf("\033[42;35mthis is //annotation\033[0m\n");
	#endif
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 368 "lexical.l"
{
	char c1 = input();
	while (1) {
		//printf("c1c2: %c%c %d %d\n", c1, c2, c1, c2);
		if((c1=='*')){
			char c2 = input();
			if(c2 == '/') {
				#ifdef LEX
				printf("\033[42;35mthis is /**/annotation\033[0m\n");
				#endif
				break;
			}
		}
		if(c1 == -1) {
			#ifdef LEX
			printf("this is read end\n");
			#endif
			is_error = 1;
			yyerror("SYNTAX ERROR");
			break;
		}	
		c1 = input();
	}
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 392 "lexical.l"
{
		is_error = 1;
		//printf("\033[45;37mError type A at Line %d: Mysterious characters \'%s\'\033[0m\n", yylineno, yytext);
		printf("Error type A at Line %d: Mysterious characters \'%s\'.\n", yylineno, yytext);
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 399 "lexical.l"
ECHO;
	YY_BREAK
#line 1768 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 279);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 399 "lexical.l"




